# ----------------------------------------------------
# Base Configuration for TUN Mode (System-wide Interception)
# ----------------------------------------------------
port: 7890
socks-port: 7891
allow-lan: false
mode: rule
log-level: info
external-controller: 127.0.0.1:9090

# ----------------------------------------------------
# DNS Configuration (Recommended for privacy and Fake-IP for optimal filtering)
# ----------------------------------------------------
dns:
  enable: true
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  default-nameserver:
    - 1.1.1.1        # Cloudflare (Recommended, privacy-focused)
    - 8.8.8.8        # Google
  nameserver:
    - https://dns.cloudflare.com/dns-query # DNS over HTTPS (DoH)
    - https://dns.google/dns-query         # DNS over HTTPS (DoH)

# ----------------------------------------------------
# Proxy Definitions (Minimal: Direct and Reject actions)
# ----------------------------------------------------
proxies:
  - {name: "Direct", type: direct}
  - {name: "Reject", type: reject}

# ----------------------------------------------------
# Proxy Groups (Define actions)
# ----------------------------------------------------
proxy-groups:
  - name: BLOCK # Destination for blocked domains
    type: select
    proxies:
      - Reject

  - name: GLOBAL # Destination for all allowed traffic
    type: select
    proxies:
      - Direct

# ----------------------------------------------------
# Rule Providers (Define external lists)
# ----------------------------------------------------
rule-providers:
  # 1. WHITELIST PROVIDER (NOW WITH CORRECT URL)
  adobe_whitelist_provider:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/Aguas-da-Amazonia/Above.a.dove/refs/heads/main/Clash_Adobe_whitelist" 
    interval: 86400
    path: "./rule_providers/adobe_whitelist.yaml"

  # 2. BLOCKLIST PROVIDER
  adobe_telemetry_block:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/Aguas-da-Amazonia/Above.a.dove/refs/heads/main/Clash_Adobe_blocklist"
    interval: 86400
    path: "./rule_providers/adobe_telemetry_block.yaml"

# ----------------------------------------------------
# Rules Section (Order is CRITICAL: Whitelist must be first)
# ----------------------------------------------------
rules:
  # 1. WHITELIST: Send specific services directly (Highest priority)
  - RULE-SET,adobe_whitelist_provider,GLOBAL

  # 2. BLOCKLIST: Reject all broader telemetry (Lower priority)
  - RULE-SET,adobe_telemetry_block,BLOCK

  # 3. Block internal loopback and private addresses
  - IP-CIDR,127.0.0.0/8,Reject,no-resolve
  - IP-CIDR,10.0.0.0/8,Reject,no-resolve
  - IP-CIDR,172.16.0.0/12,Reject,no-resolve
  - IP-CIDR,192.168.0.0/16,Reject,no-resolve

  # 4. FINAL FALLBACK: Send everything else directly to the Internet
  - MATCH,GLOBAL
